<?php
require_once 'common.php';
header('Content-Type:text/css');
header('Cache-control:private, no-cache, no-store, max-age=0');
header('Pragma:no-cache');
?>
/* Dynamically generated by Randomize CSS Wordpress Plugin http://blog.fleischer.hu/wordpress/randimize-css/ */
<?php

echo randomize_css_process_tpl_dir();
